- pom.xml
* Missed active support version
> updated active support version

- pom.xml
- src/main/java/apiCalls/Utils/generic/BaseAPI.java
- src/main/java/apiCalls/actions/AccessToken.java
- src/main/java/apiCalls/actions/CreateApplication.java
- src/main/java/apiCalls/actions/GetApplicationDetails.java
- src/main/java/apiCalls/actions/GrantLicence.java
- src/main/java/apiCalls/actions/InternalDetails.java
* Added syncronized blocks for methods to avoid race condition bug
* Classes are now extending the BasePage instead of Instantiating 
> access token improvements

- pom.xml
- src/main/java/apiCalls/Utils/generic/BaseAPI.java
- src/main/java/apiCalls/Utils/generic/Headers.java
- src/main/java/apiCalls/actions/CreateApplication.java
- src/main/java/apiCalls/actions/GetApplicationDetails.java
- src/main/java/apiCalls/actions/GrantLicence.java
- src/main/java/apiCalls/actions/InternalDetails.java
- src/main/java/apiCalls/actions/RegisterUser.java
- src/main/java/apiCalls/actions/Token.java
- src/main/java/apiCalls/actions/UpdateLicence.java
- src/main/java/apiCalls/actions/UserDetails.java
- src/main/java/apiCalls/eupaActions/BaseAPI.java
- src/main/java/apiCalls/eupaActions/external/UserAPI.java
- src/main/java/apiCalls/eupaActions/internal/CaseWorkerAPI.java
- src/main/java/apiCalls/eupaActions/internal/IrhpPermitStockAPI.java
- src/main/java/apiCalls/eupaActions/internal/IrhpPermitWindowAPI.java
- src/main/java/apiCalls/eupaActions/internal/LicenceAPI.java
- src/main/java/apiCalls/eupaActions/util/Utils.java
* The `getAdminToken` method has been made more efficient to help reduce optimistic locks against backend api 
> Optimistic lock

- pom.xml
> feat:added dependent repos in pom

- pom.xml
> feat: added repos

- pom.xml
> feat: add urls

- .github/workflows/maven-publish.yml
> fix:workflow error

- pom.xml
> fix: mirrors

- pom.xml
> fix: mirror url

- pom.xml
> feat:up pom version

- .github/workflows/maven-publish.yml
- pom.xml
> feat: github packages

- .github/workflows/cd.yaml
- .github/workflows/maven.yaml
- pom.xml
> feat:  vol 5246b - test dependancy workflows

- .github/workflows/maven.yaml
- pom.xml
> Feat vol 5246b

- pom.xml
> feat:Update pom.xml

- README.md
> feat:Update README.md

- pom.xml
> fix:Update pom.xml

- pom.xml
> feat:remove packaging type 

- pom.xml
- src/main/java/apiCalls/Utils/volBuilders/OverviewBuilder.java
- src/main/java/apiCalls/actions/GrantLicence.java
Added missing field that has recently been added regarding if an application has been referred to a public inquiry.  
This was the possible cause to the 433 errors we have been seeing. 
[VOL-5246 JIRA Ticket ](https://dvsa.atlassian.net/browse/VOL-5426)
> Missing field

- .snyk
- pom.xml
Dom4j should be addressed when we move to Java 17 
> chore : snyk 

- .snyk
- pom.xml
> chore:up active support version

- src/main/java/apiCalls/actions/RegisterUser.java
> chore:thread safety for register user

- .snyk
- pom.xml
> chore: downngrade/remove snakeyaml

- .snyk
- pom.xml
- src/main/java/apiCalls/Utils/generic/BaseAPI.java
- src/main/java/apiCalls/Utils/http/RestUtils.java
- src/main/java/apiCalls/actions/CreateApplication.java
- src/main/java/apiCalls/actions/GetApplicationDetails.java
- src/main/java/apiCalls/actions/GrantLicence.java
- src/main/java/apiCalls/actions/InternalDetails.java
- src/main/java/apiCalls/actions/RegisterConsultantAndOperator.java
- src/main/java/apiCalls/actions/RegisterUser.java
- src/main/java/apiCalls/actions/Token.java
- src/main/java/apiCalls/actions/UpdateLicence.java
- src/main/java/apiCalls/actions/UserDetails.java
- src/main/java/apiCalls/eupaActions/EupaBaseAPI.java
- src/main/java/apiCalls/eupaActions/OrganisationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/ApplicationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/ECMTPermitApplicationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/UserAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/ApplicationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/AvailableTypesAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/OpenWindowsAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/PermitTypeAPIEupa.java
- src/main/java/apiCalls/eupaActions/internal/CaseWorkerAPIEupa.java
- src/main/java/apiCalls/eupaActions/internal/IrhpPermitStockAPIEupa.java
- src/main/java/apiCalls/eupaActions/internal/IrhpPermitWindowAPI.java
- src/main/java/apiCalls/eupaActions/internal/LicenceAPIEupa.java
> java 17 upgrade 

- pom.xml
- src/main/java/apiCalls/Utils/generic/BaseAPI.java
- src/main/java/apiCalls/actions/CreateApplication.java
- src/main/java/apiCalls/actions/GetApplicationDetails.java
- src/main/java/apiCalls/actions/GrantLicence.java
- src/main/java/apiCalls/actions/InternalDetails.java
- src/main/java/apiCalls/actions/RegisterConsultantAndOperator.java
- src/main/java/apiCalls/actions/RegisterUser.java
- src/main/java/apiCalls/actions/Token.java
- src/main/java/apiCalls/actions/UpdateLicence.java
- src/main/java/apiCalls/actions/UserDetails.java
- src/main/java/apiCalls/eupaActions/EupaBaseAPI.java
- src/main/java/apiCalls/eupaActions/OrganisationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/ApplicationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/ECMTPermitApplicationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/UserAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/ApplicationAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/AvailableTypesAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/OpenWindowsAPIEupa.java
- src/main/java/apiCalls/eupaActions/external/permits/PermitTypeAPIEupa.java
- src/main/java/apiCalls/eupaActions/internal/CaseWorkerAPIEupa.java
- src/main/java/apiCalls/eupaActions/internal/IrhpPermitStockAPIEupa.java
- src/main/java/apiCalls/eupaActions/internal/IrhpPermitWindowAPI.java
- src/main/java/apiCalls/eupaActions/internal/LicenceAPIEupa.java
> fix: refactor for refactored uri constructor

- pom.xml
> fix: update active support

- pom.xml
> fix: updated active support

- pom.xml
> fix: bump up lang3

- src/main/java/apiCalls/actions/CreateApplication.java
> fix: comment out

- pom.xml
> fix: netty
